### ISSUE TITLE
Multiple commands produce Assets.car

### ISSUE THREAD

**Issue by harshal-moneylion** [AdaSupport/ios-sdk#16]
Hello We are getting following issue

`error: Multiple commands produce '/Users/vagrant/Library/Developer/Xcode/DerivedData/MoneyLion-cjkkckuauujkmtcvovgeomsticpl/Build/Intermediates.noindex/ArchiveIntermediates/XXX-Beta/InstallationBuildProductsLocation/Applications/XXX.app/Assets.car'`

Environment we are using

Xcode : Version 12.2 (12B45b)
AdaEmbedFramework : 1.3.1
Build system : New Build System (as old one is deprecated)

**Comment by harshal-moneylion** [comment]
@NicHaley @aaronvegh 
do take a look at https://github.com/AdaSupport/ios-sdk/pull/17
for reference

**Comment by harshal-moneylion** [comment]
Hello guys,

Just following up.

**Comment by harshal-moneylion** [comment]
Hello @NicHaley @aaronvegh Did you guys managed to take a look at this issue?

**Comment by NicHaley** [comment]
Hi @harshal-moneylion ! I no longer am at Ada, but I've pinged some people to take a look :)

**Comment by sevarubbo** [comment]
Hi @harshal-moneylion. We will look into the issue after the holiday break next year if that's ok. Happy holidays!

**Comment by harshal-moneylion** [comment]
@sevarubbo thanks for acknowledging, 
Surely can take look whenever you guys are available. Happy holidays. 
We are using the fork with the fix and that works. so no hurry

**Comment by saraht129** [comment]
@sevarubbo pinging on this again, appreciate some progress here so we don't miss out on your new updates in the future. Thanks!

**Comment by harshal-moneylion** [comment]
@sevarubbo Wanted to follow up on this is there any progress??

**Comment by kellylara** [comment]
Hi @harshal-moneylion and @saraht129, thank you for your patience on this issue. The team does have this in their queue, and this is behind a few other issues. @leejtimothy and I will keep everyone updated on when work on this issue begins.

**Comment by harshal-moneylion** [comment]
@kellylara Just wanted to check any luck on this issue. Did it managed to get ahed in the queue???

**Comment by 942v** [comment]
@kellylara Please just accept @harshal-moneylion PR, that fixes the issue, only testing is needed

**Comment by harshal-moneylion** [comment]
Hello @kellylara,

Hope you are doing well.
It's been a while we heard from you.

Did you guys manage to take a look at the issue? And managed to see if this can attract higher priority on your queue.

**Comment by shede333** [comment]
> Hello @kellylara,
> 
> Hope you are doing well.
> It's been a while we heard from you.
> 
> Did you guys manage to take a look at the issue? And managed to see if this can attract higher priority on your queue.

me too!!!

**Comment by Abi8773** [comment]
Apologies for the delayed responses. This task is in the team's backlog, and they hope to start work on this in the next couple of weeks. 

I have also bought into attenion #17 by @harshal-moneylion  with the team and will update this thread as soon as I hear back from the team.

**Comment by DilipLohar123** [comment]
For solution  :
Removed ${CONFIGURATION}-input-files.xcfilelist File from the input file and output file in [CP] Copy Pods Resources
